jobs:
#####    POSTGRES_POC     ###### 
  - server_name: "postgres_server_poc"
    database: "postgres_db_poc"
    table_name: "eq_copy"
    schema_name: "dbo"
    incremental_date: "bc_date"
    n: 5

  - server_name: "postgres_server_poc"
    database: "postgres_db_poc"
    table_name: "drv_copy"
    schema_name: "dbo"
    incremental_date: "bc_date"
    n: 5

  - server_name: "postgres_server_poc"
    database: "postgres_db_poc"
    table_name: "mcx_copy"
    schema_name: "dbo"
    incremental_date: "bc_date"
    n: 5