jobs:
#####    MYSQL_POC     ###### 
  - server_name: "mysql_server_poc"
    database: "mysql_db_poc"
    table_name: "connected_users"
    incremental_date: "activitytime"
    n: 5

  - server_name: "mysql_server_poc"
    database: "mysql_db_poc"
    table_name: "orderdetails"
    incremental_date: "Order_Timestamp"
    n: 5
