jobs:
#####    ORACLE_POC    ###### 
  - server_name: "oracle_server_poc"
    schema: "oracle_schema_poc"
    database: "oracle_db_poc"
    table_name: "sh01"
    incremental_date: "trdate"
    n: 3

  - server_name: "oracle_server_poc"
    schema: "oracle_schema_poc"
    database: "oracle_db_poc"
    table_name: "fo01"
    incremental_date: "trdate"
    n: 3